import * as fs   from 'fs'
import * as path from 'path'
import type { UEProject } from '../types'

// ── Templates ─────────────────────────────────────────────────────────────────

const GITATTRIBUTES = `# Unreal Engine 5 – Git Attributes
# Generated by Lucid Git  (safe to edit, do not delete the filter=lfs lines)

# ── Text auto-detection ────────────────────────────────────────────────────────
*          text=auto

# ── Source / config ───────────────────────────────────────────────────────────
*.cs       text eol=crlf
*.h        text eol=crlf
*.cpp      text eol=crlf
*.inl      text eol=crlf
*.c        text eol=crlf
*.ini      text eol=crlf
*.cfg      text eol=crlf
*.bat      text eol=crlf
*.sh       text eol=lf
*.json     text eol=lf
*.xml      text eol=lf
*.yaml     text eol=lf
*.yml      text eol=lf
*.md       text eol=lf
*.uproject text eol=lf
*.uplugin  text eol=lf

# ── Unreal Engine assets — lockable so LFS enforces checkout-before-edit ──────
*.uasset   filter=lfs diff=lfs merge=lfs -text lockable
*.umap     filter=lfs diff=lfs merge=lfs -text lockable
*.upk      filter=lfs diff=lfs merge=lfs -text lockable
*.udk      filter=lfs diff=lfs merge=lfs -text lockable

# ── Images ────────────────────────────────────────────────────────────────────
*.png      filter=lfs diff=lfs merge=lfs -text
*.jpg      filter=lfs diff=lfs merge=lfs -text
*.jpeg     filter=lfs diff=lfs merge=lfs -text
*.gif      filter=lfs diff=lfs merge=lfs -text
*.bmp      filter=lfs diff=lfs merge=lfs -text
*.tga      filter=lfs diff=lfs merge=lfs -text
*.dds      filter=lfs diff=lfs merge=lfs -text
*.exr      filter=lfs diff=lfs merge=lfs -text
*.hdr      filter=lfs diff=lfs merge=lfs -text
*.tiff     filter=lfs diff=lfs merge=lfs -text
*.tif      filter=lfs diff=lfs merge=lfs -text
*.psd      filter=lfs diff=lfs merge=lfs -text
*.xcf      filter=lfs diff=lfs merge=lfs -text

# ── Audio ─────────────────────────────────────────────────────────────────────
*.wav      filter=lfs diff=lfs merge=lfs -text
*.mp3      filter=lfs diff=lfs merge=lfs -text
*.ogg      filter=lfs diff=lfs merge=lfs -text
*.flac     filter=lfs diff=lfs merge=lfs -text
*.aif      filter=lfs diff=lfs merge=lfs -text
*.aiff     filter=lfs diff=lfs merge=lfs -text

# ── Video ─────────────────────────────────────────────────────────────────────
*.mp4      filter=lfs diff=lfs merge=lfs -text
*.avi      filter=lfs diff=lfs merge=lfs -text
*.mov      filter=lfs diff=lfs merge=lfs -text
*.wmv      filter=lfs diff=lfs merge=lfs -text
*.mkv      filter=lfs diff=lfs merge=lfs -text

# ── 3D / Meshes ───────────────────────────────────────────────────────────────
*.fbx      filter=lfs diff=lfs merge=lfs -text
*.obj      filter=lfs diff=lfs merge=lfs -text
*.abc      filter=lfs diff=lfs merge=lfs -text
*.ma       filter=lfs diff=lfs merge=lfs -text
*.mb       filter=lfs diff=lfs merge=lfs -text
*.blend    filter=lfs diff=lfs merge=lfs -text
*.3ds      filter=lfs diff=lfs merge=lfs -text
*.max      filter=lfs diff=lfs merge=lfs -text
*.ztl      filter=lfs diff=lfs merge=lfs -text

# ── Fonts ─────────────────────────────────────────────────────────────────────
*.ttf      filter=lfs diff=lfs merge=lfs -text
*.otf      filter=lfs diff=lfs merge=lfs -text
*.woff     filter=lfs diff=lfs merge=lfs -text
*.woff2    filter=lfs diff=lfs merge=lfs -text

# ── Archives / Compiled ───────────────────────────────────────────────────────
*.zip      filter=lfs diff=lfs merge=lfs -text
*.7z       filter=lfs diff=lfs merge=lfs -text
*.rar      filter=lfs diff=lfs merge=lfs -text
*.pak      filter=lfs diff=lfs merge=lfs -text
*.dll      filter=lfs diff=lfs merge=lfs -text
*.exe      filter=lfs diff=lfs merge=lfs -text
*.lib      filter=lfs diff=lfs merge=lfs -text
*.a        filter=lfs diff=lfs merge=lfs -text
*.so       filter=lfs diff=lfs merge=lfs -text
*.dylib    filter=lfs diff=lfs merge=lfs -text
*.pdf      filter=lfs diff=lfs merge=lfs -text
`

const GITIGNORE = `# Unreal Engine 5 – Git Ignore
# Generated by Lucid Git

# ── Unreal build / cache directories ─────────────────────────────────────────
Binaries/
Build/
Intermediate/
Saved/
DerivedDataCache/
FileOpenOrder/
Releases/

# ── Unreal project files generated by the engine ─────────────────────────────
*.sln
*.suo
*.user

# ── Visual Studio ─────────────────────────────────────────────────────────────
.vs/
*.VC.db
*.opensdf
*.opendb

# ── JetBrains Rider ───────────────────────────────────────────────────────────
.idea/
*.iml

# ── Xcode ─────────────────────────────────────────────────────────────────────
*.xcworkspace
*.xcodeproj

# ── Windows ───────────────────────────────────────────────────────────────────
Thumbs.db
Desktop.ini
$RECYCLE.BIN/
*.lnk

# ── macOS ─────────────────────────────────────────────────────────────────────
.DS_Store
.AppleDouble
.LSOverride
._*

# ── Logs ──────────────────────────────────────────────────────────────────────
*.log

# ── Plugins (remove line below if you track plugin source code) ───────────────
# Plugins/
`

// ── INI helpers ───────────────────────────────────────────────────────────────

/**
 * Merge key=value pairs into an INI section, preserving all other content.
 * Creates the section if it does not exist.
 */
function setIniKeys(content: string, section: string, keys: Record<string, string>): string {
  const lines = content.split('\n')
  const header = `[${section}]`

  let secIdx = lines.findIndex(l => l.trimEnd() === header)

  if (secIdx === -1) {
    const appended = ['', header, ...Object.entries(keys).map(([k, v]) => `${k}=${v}`)]
    return (content.trimEnd() ? content.trimEnd() + '\n' : '') + appended.join('\n') + '\n'
  }

  let endIdx = lines.length
  for (let i = secIdx + 1; i < lines.length; i++) {
    if (lines[i].trimStart().startsWith('[')) { endIdx = i; break }
  }

  const remaining = new Set(Object.keys(keys))
  for (let i = secIdx + 1; i < endIdx; i++) {
    const eqIdx = lines[i].indexOf('=')
    if (eqIdx > 0) {
      const k = lines[i].slice(0, eqIdx).trim()
      if (keys[k] !== undefined) {
        lines[i] = `${k}=${keys[k]}`
        remaining.delete(k)
      }
    }
  }
  lines.splice(endIdx, 0, ...[...remaining].map(k => `${k}=${keys[k]}`))

  return lines.join('\n')
}

// ── Service ───────────────────────────────────────────────────────────────────

export interface UESetupStatus {
  hasGitattributes:    boolean
  hasUeGitattributes:  boolean   // .gitattributes has filter=lfs for .uasset
  hasGitignore:        boolean
  hasUeGitignore:      boolean   // .gitignore has Binaries/ excluded
}

class UnrealService {
  /** Scan the repository root for a .uproject file and return project info. */
  detect(repoPath: string): UEProject | null {
    let entries: string[]
    try { entries = fs.readdirSync(repoPath) } catch { return null }

    const uprojectFile = entries.find(f => f.endsWith('.uproject'))
    if (!uprojectFile) return null

    const uprojectPath = path.join(repoPath, uprojectFile)
    try {
      const raw = JSON.parse(fs.readFileSync(uprojectPath, 'utf-8')) as Record<string, unknown>
      return {
        name:          uprojectFile.replace('.uproject', ''),
        uprojectPath,
        engineVersion: String(raw['EngineAssociation'] ?? 'Unknown'),
      }
    } catch {
      return {
        name:          uprojectFile.replace('.uproject', ''),
        uprojectPath,
        engineVersion: 'Unknown',
      }
    }
  }

  /** Return whether .gitattributes / .gitignore already contain UE-specific entries. */
  setupStatus(repoPath: string): UESetupStatus {
    const attrPath   = path.join(repoPath, '.gitattributes')
    const ignorePath = path.join(repoPath, '.gitignore')

    let hasGitattributes   = false
    let hasUeGitattributes = false
    let hasGitignore       = false
    let hasUeGitignore     = false

    try {
      const content = fs.readFileSync(attrPath, 'utf-8')
      hasGitattributes   = true
      hasUeGitattributes = content.includes('filter=lfs') && content.includes('.uasset')
    } catch {}

    try {
      const content = fs.readFileSync(ignorePath, 'utf-8')
      hasGitignore   = true
      hasUeGitignore = content.includes('Binaries/') || content.includes('Intermediate/')
    } catch {}

    return { hasGitattributes, hasUeGitattributes, hasGitignore, hasUeGitignore }
  }

  /** Write (or overwrite) .gitattributes with the UE5 LFS template. */
  writeGitattributes(repoPath: string): void {
    fs.writeFileSync(path.join(repoPath, '.gitattributes'), GITATTRIBUTES, 'utf-8')
  }

  /** Write (or overwrite) .gitignore with the UE5 template. */
  writeGitignore(repoPath: string): void {
    fs.writeFileSync(path.join(repoPath, '.gitignore'), GITIGNORE, 'utf-8')
  }

  /** Return the raw template strings for preview in the UI. */
  templates() {
    return { gitattributes: GITATTRIBUTES, gitignore: GITIGNORE }
  }

  /**
   * Check whether UEGitPlugin (GitSourceControl) is installed.
   * Checks project Plugins/, then the engine installation.
   * Returns the folder name and location so the UI can show the exact path.
   */
  pluginStatus(repoPath: string): {
    installed: boolean
    location: 'project' | 'engine' | null
    pluginFolder: string | null
  } {
    // Possible folder names — ordered by preference
    const FOLDER_NAMES = ['UEGitPlugin', 'GitSourceControl', 'UEGitPlugin-main']
    const UPLUGIN = 'GitSourceControl.uplugin'

    // 1. Project-level — best option: plugin ships with the repo
    for (const folder of FOLDER_NAMES) {
      if (fs.existsSync(path.join(repoPath, 'Plugins', folder, UPLUGIN))) {
        return { installed: true, location: 'project', pluginFolder: folder }
      }
    }

    // 2. Engine-level — works for this user but teammates need their own install
    const project = this.detect(repoPath)
    const version = project?.engineVersion ?? ''
    if (/^\d+\.\d+/.test(version)) {
      const ueFolder = `UE_${version}`
      const engineRoots: string[] = []

      if (process.platform === 'win32') {
        const pf  = process.env['PROGRAMFILES']     ?? 'C:\\Program Files'
        const pf86 = process.env['PROGRAMFILES(X86)'] ?? 'C:\\Program Files (x86)'
        engineRoots.push(
          path.join(pf,   'Epic Games', ueFolder),
          path.join(pf86, 'Epic Games', ueFolder),
        )
      } else if (process.platform === 'darwin') {
        engineRoots.push(
          path.join('/Users', 'Shared', 'Epic Games', ueFolder),
          path.join('/Library', 'Application Support', 'Epic', 'UnrealEngine', ueFolder),
        )
      }

      const ENGINE_SUBDIRS = ['Developer', 'Marketplace', 'Editor', 'Runtime', '']
      for (const root of engineRoots) {
        for (const sub of ENGINE_SUBDIRS) {
          for (const folder of FOLDER_NAMES) {
            const candidate = sub
              ? path.join(root, 'Engine', 'Plugins', sub, folder, UPLUGIN)
              : path.join(root, 'Engine', 'Plugins', folder, UPLUGIN)
            if (fs.existsSync(candidate)) {
              return { installed: true, location: 'engine', pluginFolder: folder }
            }
          }
        }
      }
    }

    return { installed: false, location: null, pluginFolder: null }
  }

  /** Read current state of the two UE config files that affect source control. */
  ueConfigStatus(repoPath: string): {
    editorConfigExists: boolean
    editorConfigHasSccSettings: boolean
    editorConfigHasCheckoutSettings: boolean
    engineConfigExists: boolean
    engineConfigHasSkipCheck: boolean
  } {
    const editorPath = path.join(repoPath, 'Config', 'DefaultEditorPerProjectUserSettings.ini')
    const enginePath = path.join(repoPath, 'Config', 'DefaultEngine.ini')

    let editorContent = ''
    let engineContent = ''
    try { editorContent = fs.readFileSync(editorPath, 'utf-8') } catch {}
    try { engineContent = fs.readFileSync(enginePath, 'utf-8') } catch {}

    return {
      editorConfigExists:          editorContent.length > 0,
      editorConfigHasSccSettings:  editorContent.includes('bSCCAutoAddNewFiles=False'),
      editorConfigHasCheckoutSettings: editorContent.includes('bAutomaticallyCheckoutOnAssetModification=True'),
      engineConfigExists:          engineContent.length > 0,
      engineConfigHasSkipCheck:    engineContent.includes('r.Editor.SkipSourceControlCheckForEditablePackages=1'),
    }
  }

  /**
   * Write (or merge into) Config/DefaultEditorPerProjectUserSettings.ini.
   * Sets source control checkout behaviour for the GitSourceControl plugin workflow.
   * Preserves all existing content.
   */
  writeEditorConfig(repoPath: string): void {
    const configDir = path.join(repoPath, 'Config')
    fs.mkdirSync(configDir, { recursive: true })
    const filePath = path.join(configDir, 'DefaultEditorPerProjectUserSettings.ini')

    let content = ''
    try { content = fs.readFileSync(filePath, 'utf-8') } catch {}

    // Prevents UE from auto-adding new files to source control (Lucid Git manages staging)
    content = setIniKeys(content, '/Script/SourceControl.SCC_PackageSettings', {
      bSCCAutoAddNewFiles: 'False',
    })

    // Makes the editor lock (checkout) assets automatically when you open them for edit
    content = setIniKeys(content, '/Script/UnrealEd.EditorLoadingSavingSettings', {
      bAutomaticallyCheckoutOnAssetModification: 'True',
      bPromptForCheckoutOnAssetModification:     'False',
      bAutoloadCheckedOutPackages:               'True',
    })

    fs.writeFileSync(filePath, content, 'utf-8')
  }

  /**
   * Write (or merge into) Config/DefaultEngine.ini.
   * Disables the read-only file check that conflicts with LFS lock workflows.
   * Preserves all existing content.
   */
  writeEngineConfig(repoPath: string): void {
    const configDir = path.join(repoPath, 'Config')
    fs.mkdirSync(configDir, { recursive: true })
    const filePath = path.join(configDir, 'DefaultEngine.ini')

    let content = ''
    try { content = fs.readFileSync(filePath, 'utf-8') } catch {}

    content = setIniKeys(content, 'ConsoleVariables', {
      'r.Editor.SkipSourceControlCheckForEditablePackages': '1',
    })

    fs.writeFileSync(filePath, content, 'utf-8')
  }

  /**
   * Sum the on-disk size of staged paths that match LFS binary patterns.
   * Used to warn before committing a large batch of raw assets.
   */
  pakSizeEstimate(repoPath: string, stagedPaths: string[]): number {
    const LFS_EXTS = new Set([
      'uasset','umap','upk','udk','ubulk','uexp','ucas',
      'png','jpg','jpeg','gif','bmp','tga','dds','exr','hdr','tiff','tif','psd',
      'wav','mp3','ogg','flac','aif','aiff',
      'mp4','avi','mov','wmv','mkv',
      'fbx','obj','abc','ma','mb','blend',
      'pak','zip','7z','rar','dll','exe','lib','so','dylib','pdf',
    ])
    let total = 0
    for (const rel of stagedPaths) {
      const ext = rel.split('.').pop()?.toLowerCase() ?? ''
      if (!LFS_EXTS.has(ext)) continue
      try { total += fs.statSync(path.join(repoPath, rel)).size } catch {}
    }
    return total
  }
}

export const unrealService = new UnrealService()
