import * as fs   from 'fs'
import * as path from 'path'
import type { UEProject } from '../types'

// ── Templates ─────────────────────────────────────────────────────────────────

const GITATTRIBUTES = `# Unreal Engine 5 – Git Attributes
# Generated by Lucid Git  (safe to edit, do not delete the filter=lfs lines)

# ── Text auto-detection ────────────────────────────────────────────────────────
*          text=auto

# ── Source / config ───────────────────────────────────────────────────────────
*.cs       text eol=crlf
*.h        text eol=crlf
*.cpp      text eol=crlf
*.inl      text eol=crlf
*.c        text eol=crlf
*.ini      text eol=crlf
*.cfg      text eol=crlf
*.bat      text eol=crlf
*.sh       text eol=lf
*.json     text eol=lf
*.xml      text eol=lf
*.yaml     text eol=lf
*.yml      text eol=lf
*.md       text eol=lf
*.uproject text eol=lf
*.uplugin  text eol=lf

# ── Unreal Engine assets ───────────────────────────────────────────────────────
*.uasset   filter=lfs diff=lfs merge=lfs -text
*.umap     filter=lfs diff=lfs merge=lfs -text
*.upk      filter=lfs diff=lfs merge=lfs -text
*.udk      filter=lfs diff=lfs merge=lfs -text

# ── Images ────────────────────────────────────────────────────────────────────
*.png      filter=lfs diff=lfs merge=lfs -text
*.jpg      filter=lfs diff=lfs merge=lfs -text
*.jpeg     filter=lfs diff=lfs merge=lfs -text
*.gif      filter=lfs diff=lfs merge=lfs -text
*.bmp      filter=lfs diff=lfs merge=lfs -text
*.tga      filter=lfs diff=lfs merge=lfs -text
*.dds      filter=lfs diff=lfs merge=lfs -text
*.exr      filter=lfs diff=lfs merge=lfs -text
*.hdr      filter=lfs diff=lfs merge=lfs -text
*.tiff     filter=lfs diff=lfs merge=lfs -text
*.tif      filter=lfs diff=lfs merge=lfs -text
*.psd      filter=lfs diff=lfs merge=lfs -text
*.xcf      filter=lfs diff=lfs merge=lfs -text

# ── Audio ─────────────────────────────────────────────────────────────────────
*.wav      filter=lfs diff=lfs merge=lfs -text
*.mp3      filter=lfs diff=lfs merge=lfs -text
*.ogg      filter=lfs diff=lfs merge=lfs -text
*.flac     filter=lfs diff=lfs merge=lfs -text
*.aif      filter=lfs diff=lfs merge=lfs -text
*.aiff     filter=lfs diff=lfs merge=lfs -text

# ── Video ─────────────────────────────────────────────────────────────────────
*.mp4      filter=lfs diff=lfs merge=lfs -text
*.avi      filter=lfs diff=lfs merge=lfs -text
*.mov      filter=lfs diff=lfs merge=lfs -text
*.wmv      filter=lfs diff=lfs merge=lfs -text
*.mkv      filter=lfs diff=lfs merge=lfs -text

# ── 3D / Meshes ───────────────────────────────────────────────────────────────
*.fbx      filter=lfs diff=lfs merge=lfs -text
*.obj      filter=lfs diff=lfs merge=lfs -text
*.abc      filter=lfs diff=lfs merge=lfs -text
*.ma       filter=lfs diff=lfs merge=lfs -text
*.mb       filter=lfs diff=lfs merge=lfs -text
*.blend    filter=lfs diff=lfs merge=lfs -text
*.3ds      filter=lfs diff=lfs merge=lfs -text
*.max      filter=lfs diff=lfs merge=lfs -text
*.ztl      filter=lfs diff=lfs merge=lfs -text

# ── Fonts ─────────────────────────────────────────────────────────────────────
*.ttf      filter=lfs diff=lfs merge=lfs -text
*.otf      filter=lfs diff=lfs merge=lfs -text
*.woff     filter=lfs diff=lfs merge=lfs -text
*.woff2    filter=lfs diff=lfs merge=lfs -text

# ── Archives / Compiled ───────────────────────────────────────────────────────
*.zip      filter=lfs diff=lfs merge=lfs -text
*.7z       filter=lfs diff=lfs merge=lfs -text
*.rar      filter=lfs diff=lfs merge=lfs -text
*.pak      filter=lfs diff=lfs merge=lfs -text
*.dll      filter=lfs diff=lfs merge=lfs -text
*.exe      filter=lfs diff=lfs merge=lfs -text
*.lib      filter=lfs diff=lfs merge=lfs -text
*.a        filter=lfs diff=lfs merge=lfs -text
*.so       filter=lfs diff=lfs merge=lfs -text
*.dylib    filter=lfs diff=lfs merge=lfs -text
*.pdf      filter=lfs diff=lfs merge=lfs -text
`

const GITIGNORE = `# Unreal Engine 5 – Git Ignore
# Generated by Lucid Git

# ── Unreal build / cache directories ─────────────────────────────────────────
Binaries/
Build/
Intermediate/
Saved/
DerivedDataCache/
FileOpenOrder/
Releases/

# ── Unreal project files generated by the engine ─────────────────────────────
*.sln
*.suo
*.user

# ── Visual Studio ─────────────────────────────────────────────────────────────
.vs/
*.VC.db
*.opensdf
*.opendb

# ── JetBrains Rider ───────────────────────────────────────────────────────────
.idea/
*.iml

# ── Xcode ─────────────────────────────────────────────────────────────────────
*.xcworkspace
*.xcodeproj

# ── Windows ───────────────────────────────────────────────────────────────────
Thumbs.db
Desktop.ini
$RECYCLE.BIN/
*.lnk

# ── macOS ─────────────────────────────────────────────────────────────────────
.DS_Store
.AppleDouble
.LSOverride
._*

# ── Logs ──────────────────────────────────────────────────────────────────────
*.log

# ── Plugins (remove line below if you track plugin source code) ───────────────
# Plugins/
`

// ── Service ───────────────────────────────────────────────────────────────────

export interface UESetupStatus {
  hasGitattributes:    boolean
  hasUeGitattributes:  boolean   // .gitattributes has filter=lfs for .uasset
  hasGitignore:        boolean
  hasUeGitignore:      boolean   // .gitignore has Binaries/ excluded
}

class UnrealService {
  /** Scan the repository root for a .uproject file and return project info. */
  detect(repoPath: string): UEProject | null {
    let entries: string[]
    try { entries = fs.readdirSync(repoPath) } catch { return null }

    const uprojectFile = entries.find(f => f.endsWith('.uproject'))
    if (!uprojectFile) return null

    const uprojectPath = path.join(repoPath, uprojectFile)
    try {
      const raw = JSON.parse(fs.readFileSync(uprojectPath, 'utf-8')) as Record<string, unknown>
      return {
        name:          uprojectFile.replace('.uproject', ''),
        uprojectPath,
        engineVersion: String(raw['EngineAssociation'] ?? 'Unknown'),
      }
    } catch {
      return {
        name:          uprojectFile.replace('.uproject', ''),
        uprojectPath,
        engineVersion: 'Unknown',
      }
    }
  }

  /** Return whether .gitattributes / .gitignore already contain UE-specific entries. */
  setupStatus(repoPath: string): UESetupStatus {
    const attrPath   = path.join(repoPath, '.gitattributes')
    const ignorePath = path.join(repoPath, '.gitignore')

    let hasGitattributes   = false
    let hasUeGitattributes = false
    let hasGitignore       = false
    let hasUeGitignore     = false

    try {
      const content = fs.readFileSync(attrPath, 'utf-8')
      hasGitattributes   = true
      hasUeGitattributes = content.includes('filter=lfs') && content.includes('.uasset')
    } catch {}

    try {
      const content = fs.readFileSync(ignorePath, 'utf-8')
      hasGitignore   = true
      hasUeGitignore = content.includes('Binaries/') || content.includes('Intermediate/')
    } catch {}

    return { hasGitattributes, hasUeGitattributes, hasGitignore, hasUeGitignore }
  }

  /** Write (or overwrite) .gitattributes with the UE5 LFS template. */
  writeGitattributes(repoPath: string): void {
    fs.writeFileSync(path.join(repoPath, '.gitattributes'), GITATTRIBUTES, 'utf-8')
  }

  /** Write (or overwrite) .gitignore with the UE5 template. */
  writeGitignore(repoPath: string): void {
    fs.writeFileSync(path.join(repoPath, '.gitignore'), GITIGNORE, 'utf-8')
  }

  /** Return the raw template strings for preview in the UI. */
  templates() {
    return { gitattributes: GITATTRIBUTES, gitignore: GITIGNORE }
  }

  /**
   * Sum the on-disk size of staged paths that match LFS binary patterns.
   * Used to warn before committing a large batch of raw assets.
   */
  pakSizeEstimate(repoPath: string, stagedPaths: string[]): number {
    const LFS_EXTS = new Set([
      'uasset','umap','upk','udk','ubulk','uexp','ucas',
      'png','jpg','jpeg','gif','bmp','tga','dds','exr','hdr','tiff','tif','psd',
      'wav','mp3','ogg','flac','aif','aiff',
      'mp4','avi','mov','wmv','mkv',
      'fbx','obj','abc','ma','mb','blend',
      'pak','zip','7z','rar','dll','exe','lib','so','dylib','pdf',
    ])
    let total = 0
    for (const rel of stagedPaths) {
      const ext = rel.split('.').pop()?.toLowerCase() ?? ''
      if (!LFS_EXTS.has(ext)) continue
      try { total += fs.statSync(path.join(repoPath, rel)).size } catch {}
    }
    return total
  }
}

export const unrealService = new UnrealService()
